#!/bin/bash

# $(docker-machine env super-useful)

docker_host=`echo "console.log(require('url').parse(process.env.DOCKER_HOST).hostname)" | node`

docker build -q -t su-db-mongodb .

docker run --name su-db-mongodb -p 27018:27017 -d su-db-mongodb

echo "su-db.test.mongodb: importing test data";
mongoimport --host $docker_host --port 27018 --db test --collection test --file ./data.json --jsonArray
