#!/bin/bash

docker build -t su-db-postgresql .

docker run -i --name su-db-postgresql -p 5433:5432 -t -d su-db-postgresql

echo "su-db.test.postgresql: importing test schema";
export PGPASSWORD="test" && psql -U test -d test -h 127.0.0.1 -p 5433 -f ./schema.sql;

echo "su-db.test.postgresql: importing test data";
export PGPASSWORD="test" && psql -U test -d test -h 127.0.0.1 -p 5433 -f ./data.sql;
