#!/bin/bash

cd ./db/redis

echo "su-db.test: initialising redis test container";

./setup

cd ../../

echo "su-db.test: initialised redis test container";

cd ./db/mongodb

echo "su-db.test: initialising mongodb test container";

./setup

cd ../../

echo "su-db.test: initialised mongodb test container";

cd ./db/rethinkdb

echo "su-db.test: initialising rethinkdb test container";

./setup

cd ../../

echo "su-db.test: initialised rethinkdb test container";

cd ./db/postgresql

echo "su-db.test: initialising postgresql test container";

./setup

cd ../../

echo "su-db.test: initialised postgresql test container";
