#!/bin/bash

echo "su-db.test: tearing down redis test container";
docker stop su-db-mongodb | xargs docker rm;

echo "su-db.test: tearing down mongodb test container";
docker stop su-db-postgresql | xargs docker rm;

echo "su-db.test: tearing down postgresql test container";
docker stop su-db-redis | xargs docker rm;

echo "all containers go bye bye!";
